-- =========================================================================
-- SCRIPT DE CRIAÇÃO E ATUALIZAÇÃO DA BASE DE DADOS DO MEUSTREAMING NO SUPABASE
-- =========================================================================
-- Abra seu painel do Supabase, clique em "SQL Editor", cole este script e clique em "Run".
-- Este script é idempotente (pode ser executado várias vezes sem gerar erros).

-- 1. TABELA DE LEADS (Triagem e Controle de Vendas)
CREATE TABLE IF NOT EXISTS leads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number text NOT NULL,
    name text,
    device text,
    screens text,
    internet text,
    wants_to_buy_today text,
    status text DEFAULT 'contatado',
    assigned_app text,
    test_sent boolean DEFAULT false,
    test_login text,
    test_password text,
    expires_at text,
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Se a tabela 'leads' já existir, adicionamos os novos campos caso não existam
ALTER TABLE leads ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS device text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS screens text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS internet text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS wants_to_buy_today text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS status text DEFAULT 'contatado';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_app text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS test_sent boolean DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS test_login text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS test_password text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS expires_at text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS notes text;

-- 2. TABELA DE BLACKLIST (Lista Negra de Números Ignorados)
CREATE TABLE IF NOT EXISTS blacklist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number text UNIQUE NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE SUPPORT_TICKETS (Chamados de Suporte e Bugs)
CREATE TABLE IF NOT EXISTS support_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number text NOT NULL,
    title text,
    description text,
    status text DEFAULT 'aberto',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABELA DE CONTENT_REQUESTS (Solicitações de Filmes/Séries)
CREATE TABLE IF NOT EXISTS content_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number text NOT NULL,
    title text NOT NULL,
    status text DEFAULT 'pendente',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices recomendados para otimização de busca
CREATE INDEX IF NOT EXISTS idx_leads_phone_number ON leads(phone_number);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_blacklist_phone ON blacklist(phone_number);
CREATE INDEX IF NOT EXISTS idx_support_status ON support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_content_status ON content_requests(status);
